apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

resources:
  - ../../secrets/nginx-secret.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: nginx
    releaseName: nginx
    chart: nginx
    valuesFile: values.yaml
