apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tamehr/chartwithsealed.git
    targetRevision: main
    path: envs/dev

    #kustomize:
      #enableHelm: true

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
