apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-main
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tamehr/chartwithsealed.git
    targetRevision: main
    path: envs/main

    kustomize:
      enableHelm: true

  destination:
    server: https://kubernetes.default.svc
    namespace: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
